version: '3'

services:
  server:
    container_name: gs-server
    build: './server'
    ports: 
      - 8080:8080
    environment:
      ES_HOST : elasticsearch
    volumes:
      - ./books:/server/books
    depends_on:
      - "elasticsearch"
    restart: 
      "on-failure"
  # client:
  #   container_name: gs-client
  #   image: nginx
  #   ports: 
  #     - 4200:4200
  #   volumes:
  #     - ./client:/usr/share/nginx/html
  #   depends_on:
  #     - "server"
  elasticsearch: # Elasticsearch Instance
    container_name: gs-search
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - logger.level=WARN
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"

volumes: # Define seperate volume for Elasticsearch data
  esdata: